Switch to libv4l-videodev.h
Thanks to Daniel Polehn for the patch

Patch from Debian bug  #621965
"vgrabbj: FTBFS: ./vgrabbj.h:45:28: fatal error: linux/videodev.h: No
such file or directory"
http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=621965